In [1]:
import jax
import jax.numpy as jnp
import requests
from PIL import Image
from transformers import AutoProcessor

from jimm.models.siglip import SigLIP

model = SigLIP(
    image_resolution=224, vision_layers=27, vision_width=1152, vision_patch_size=14, context_length=64, vocab_size=32000, transformer_width=1152, transformer_heads=16, transformer_layers=27
)

2025-07-15 23:14:55.461289: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1752621295.486223 2562305 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1752621295.494232 2562305 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1752621295.515772 2562305 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1752621295.515797 2562305 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1752621295.515799 2562305 computation_placer.cc:177] computation placer alr

In [3]:
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
HF_MODEL_NAME = "openai/clip-vit-base-patch32"
processor = AutoProcessor.from_pretrained(HF_MODEL_NAME)
inputs = jnp.transpose(processor(images=image, return_tensors="jax")["pixel_values"], axes=(0, 2, 3, 1))
print(inputs)
print(jax.jit(model.encode_image)(inputs).shape)

[[[[ 0.58728105 -1.3168719  -0.48481512]
   [ 0.58728105 -1.301864   -0.4137148 ]
   [ 0.61647785 -1.3168719  -0.38527465]
   ...
   [ 0.0617376  -1.496965   -0.95407724]
   [ 0.04713918 -1.436934   -0.8545369 ]
   [-0.02585294 -1.4819573  -0.8545369 ]]

  [[ 0.5726826  -1.241833   -0.4137148 ]
   [ 0.5726826  -1.2718486  -0.47059506]
   [ 0.66027313 -1.2268252  -0.3710546 ]
   ...
   [ 0.12013142 -1.436934   -0.81187665]
   [ 0.07633615 -1.4669495  -0.8545369 ]
   [ 0.09093457 -1.4519417  -0.78343654]]

  [[ 0.58728105 -1.2568408  -0.32839438]
   [ 0.54348576 -1.3168719  -0.4421549 ]
   [ 0.61647785 -1.2268252  -0.38527465]
   ...
   [ 0.03254076 -1.4669495  -0.86875695]
   [ 0.12013142 -1.4069184  -0.81187665]
   [ 0.0617376  -1.4519417  -0.882977  ]]

  ...

  [[ 1.8719424   0.1238739   1.5770944 ]
   [ 1.857344    0.10886613  1.6481948 ]
   [ 1.8719424   0.1238739   1.6339747 ]
   ...
   [ 1.3901944  -0.7015533   0.90875137]
   [ 1.4339896  -0.6865455   0.9514116 ]
   [ 1.4193913  